name: 07 - Using Expressions
on: 
  push:
  workflow_dispatch:
    inputs:
      debug:
        type: boolean
        default: false
jobs:
  echo:
    runs-on: ubuntu-latest
    steps:
      - name: debug Print start-up data
        if: ${{ inputs.debug == 'true' }}
        #if: ${{ inputs.debug || false }}
        run: |
          echo "Triggered by: ${{ github.event_name }}"
          echo "Branch: ${{github.ref}}"
          echo "Commit SHA: ${{github.sha}}"
          echo "Runner OS: ${{runner.os}}"

      - name: debug Print when triggered from main
        if: ${{ inputs.debug == 'true' && github.ref_name == 'main' }}
        #if: ${{ inputs.debug && github.ref == 'refs/heads/main' || false }}
        run: echo "I was triggered from main"

      - name: Greeting
        run: echo "Hello, world"

        
